export const TYPE_COMMON = {
  USD: 'USD',
  PERCENT: 'PERCENT',
  FINANCE_HEALTH: 'FINANCE_HEALTH',
};

export const COLLATERAL_TOKEN = [
  {
    name: 'WETH',
  },
  {
    name: 'WBTC',
  },
];
export const LOAN_STATUS = {
  ACTIVE: 'ACTIVE',
  REPAID_FULL: 'REPAID_FULL',
  LIQUIDATION_APPROACHING: 'LIQUIDATION_APPROACHING',
  LIQUIDATED: 'LIQUIDATED',
  DISBURSEMENT: 'DISBURSEMENT',
  UNPROCESSED: 'UNPROCESSED',
};
export const TRANSACTION_STATUS = {
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
};
export const ASSET_LIST = {
  USDC: 'USDC',
  USDT: 'USDT',
}

export const ASSET_TYPE = {
  USD: 'USD',
  FIAT: 'FIAT',
  USDT: 'USDT',
  USDC: 'USDC',
};
